#Gauss-Seidel Iteration Method (Matrix Inversion)

In [ ]:
import numpy as np
from scipy.linalg import solve

A = eval(input("Enter the matrix A : "))              # As np.array([[a11, a12], [a21, a22]])
B = eval(input("Enter the matrix B : "))              # As [b1, b2]
X = eval(input("Enter initial guess X : "))           # As [x1, x2]
n = eval(input("Enter the number of iteration : "))   # Integer input.

L = np.tril(A)
U = A-L

for i in range(n):
  X = np.dot(np.linalg.inv(L), B-np.dot(U,X))

print()
print("Solution using Gauss-Seidel Method : ", X)
print()
print("Solution using Solve Syntax : ", solve(A,B))

Enter the matrix A : [[2,1], [3,7]]
Enter the matrix B : [4,3]
Enter initial guess X : [0,0]
Enter the number of iteration : 25
Solution using Gauss-Siedel Method :  [ 2.27272727 -0.54545455]

Solution using Solve Syntax :  [ 2.27272727 -0.54545455]


# Jacobi’s Iteration method (Matrix Inversion)

In [ ]:
import numpy as np
from scipy.linalg import solve

A = eval(input("Enter the matrix A : "))              # As np.array([[a11, a12], [a21, a22]])
B = eval(input("Enter the matrix B : "))              # As [b1, b2]
X = eval(input("Enter initial guess X : "))           # As [x1, x2]
n = eval(input("Enter the number of iteration : "))   # Integer input.

D = np.diag(A)
R = A - np.diagflat(D)                                # R = L+U = Lower + Upper Triangular matrix

for i in range(n):
  X = (B - np.dot(R,X))/D

print()
print("Solution using Jacobi’s Iteration Method : ", X)
print()
print("Solution using Solve Syntax : ", solve(A,B))



Enter the matrix A : np.array([[2,1],[3,7]])
Enter the matrix B : [3,5]
Enter initial guess X : [0,0]
Enter the number of iteration : 25

Solution using Jacobi’s Iteration Method :  [1.45454545 0.0909091 ]

Solution using Solve Syntax :  [1.45454545 0.09090909]


# Determinant Method (Matrix Inversion) for 2 by 2 matrix.

In [4]:
def Transpose(m):
  return map(list, zip(*m))

def Minor(m,i,j):
  return[row[:j] + row[j+1:] for row in (m[:i] + m[i+1:])]

def Determinant(m):
  return m[0][0]*m[1][1]-m[0][1]*m[1][0]

def Inverse(m):
  determinant = Determinant(m)
  return [[m[1][1]/determinant, -1*m[0][1]/determinant],[-1*m[1][0]/determinant, m[0][0]/determinant]]

import numpy as np
m = eval(input("Enter the 2 by 2 matrix : "))      # As np.array([[a11, a12], [a21, a22]])
result = Inverse(m)
print()
print("Inverse of the above matrix : ", result)

Enter the 2 by 2 matrix : np.array([[2, -2], [1,-2]])

Inverse of the above matrix :  [[1.0, -1.0], [0.5, -1.0]]


# Determinant Method (Eigen Values & Eigen Vector)

In [6]:
import numpy as np

row = int(input("Enter the no. of rows : "))
column = int(input("Enter the no. of columns : "))

if (row == column):
  print("Enter the matrix element separated by space : ")
  entries = list(map(int, input().split(" ")))
  matrixm = np.array(entries).reshape(row, column)
  w, v = np.linalg.eig(matrixm)
  print("Matrix : ", matrixm)
  print()
  print("Eigenvalues : ", w)
  print()
  print("Eigenvectors : ", v)
else:
  print("Matrix should be square. Plz enter equal number of rows and columns.")

Enter the no. of rows : 3
Enter the no. of columns : 3
Enter the matrix element separated by space : 
1 2 4 5 6 7 4 3 2
Matrix :  [[1 2 4]
 [5 6 7]
 [4 3 2]]

Eigenvalues :  [11.31576477 -2.61940289  0.30363812]

Eigenvectors :  [[-0.32522257 -0.68368172  0.47480985]
 [-0.85043353 -0.17814591 -0.81745644]
 [-0.41351311  0.70770286  0.32606835]]


# Jacobi Method (Eigen Values & Eigen Vector)

In [10]:
from numpy import array,identity,diagonal
from math import sqrt

def Jacobi(A,tol = 1.0e-9): 
# Find largest off-diagonal element a[k,l]
 def maxElem(A): 
   n = len(A)
   Amax = 0.0
   for i in range(n-1):
     for j in range(i+1,n):
       if abs(A[i,j]) >= Amax:
         Amax = abs(A[i,j])
         k = i; l = j
   return Amax,k,l
 
# Rotate to make A[k,l] = 0 and define the rotation matrix
 def rotate(A,p,k,l): 
    n = len(A)
    Adiff = A[l,l] - A[k,k]
    if abs(A[k,l]) < abs(Adiff)*1.0e-36: 
      t = A[k,l]/Adiff
    else:
      phi = Adiff/(2.0*A[k,l])
      t = 1.0/(abs(phi) + sqrt(phi**2 + 1.0))
      if phi < 0.0: 
        t = -t
    c = 1.0/sqrt(t**2 + 1.0); s = t*c
    tau = s/(1.0 + c)
    temp = A[k,l]
    A[k,l] = 0.0
    A[k,k] = A[k,k] - t*temp
    A[l,l] = A[l,l] + t*temp
    for i in range(k): 
      temp = A[i,k]
      A[i,k] = temp - s*(A[i,l] + tau*temp)
      A[i,l] = A[i,l] + s*(temp - tau*A[i,l])
    for i in range(k+1,l):
      temp = A[k,i]
      A[k,i] = temp - s*(A[i,l] + tau*A[k,i])
      A[i,l] = A[i,l] + s*(temp - tau*A[i,l])
    for i in range(l+1,n):
      temp = A[k,i]
      A[k,i] = temp - s*(A[l,i] + tau*temp)
      A[l,i] = A[l,i] + s*(temp - tau*A[l,i])
    for i in range(n):
      temp = p[i,k]
      p[i,k] = temp - s*(p[i,l] + tau*p[i,k])
      p[i,l] = p[i,l] + s*(temp - tau*p[i,l])


 n = len(A)
 maxRot = 5*(n**2)                                 # Set limit on number of rotations
 p = identity(n)*1.0                               # Initialize transformation matrix
 for i in range(maxRot):
   Amax,k,l = maxElem(A)
   if Amax < tol: 
     return diagonal(A),p
   rotate(A,p,k,l)
 print('Jacobi method did not converge')


import numpy as np 
A = eval(input('Enter the matrix A:'))                  # as np.array([[a11,a12],[a21,a22]])    
print()            
print('Eigenvalues and Eigenvectors of matrix:\n', A)
print()
print('is\n', Jacobi(A,tol = 1.0e-9))                   # set the tolerance as your wish 

Enter the matrix A:np.array([[1,2],[2,4]])

Eigenvalues and Eigenvectors of matrix:
 [[1 2]
 [2 4]]

is
 (array([0, 5]), array([[ 0.89442719,  0.4472136 ],
       [-0.4472136 ,  0.89442719]]))


# Power Method (Eigen Values & Eigen Vector)

In [11]:
import numpy as np

A = eval(input('Enter the matrix A:'))                        # as np.array([[a11,a12],[a21,a22]])
x1 = eval(input('Enter initial guess of x:'))                 # as [x01,x02]
x2 = eval(input('Enter initial guess of x:'))                 # as [x01,x02] exactly same as x1
n = eval(input('Enter the number of Iterations:'))

for i in range (n):
 x1=np.dot(A, x1)
 norm=np.linalg.norm(x1)
 B=x1/norm
 print(B)

for i in range (n-1):
 x2=np.dot(A, x2)

C=np.min(abs(B))
eigvect=B/C

y = eval(input('Enter a non-orthogonal matrix:'))# as [y01,y02]
eigvalue=np.dot(x1,y)/np.dot(x2,y)

print('Dominating eigenvalue is', eigvalue)
print()
print('and corresponding eigenvector is', eigvect)
print()

Enter the matrix A:np.array([[1,3],[2,2]])
Enter initial guess of x:[1,0]
Enter initial guess of x:[1,0]
Enter the number of Iterations:10
[0.4472136  0.89442719]
[0.7592566  0.65079137]
[0.69310872 0.72083306]
[0.71054763 0.70364911]
[0.70624288 0.70796963]
[0.70732253 0.70689097]
[0.70705283 0.70716073]
[0.70712027 0.70709329]
[0.70710341 0.70711015]
[0.70710762 0.70710594]
Enter a non-orthogonal matrix:[1,0]
Dominating eigenvalue is 4.000028610393202

and corresponding eigenvector is [1.00000238 1.        ]



> **Created by Ved Pratap - Google Colab**